create table hotel (id bigint generated by default as identity, name varchar(255), primary key (id))
create table role (id bigint generated by default as identity, description varchar(255), role_name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, activated boolean, alias varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id))
create table user_role (user_id bigint not null, role_id bigint not null)
create table verification_token (id bigint generated by default as identity, expiry_date timestamp, token varchar(255), user_id bigint not null, primary key (id))
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user
alter table verification_token add constraint FK_VERIFY_USER foreign key (user_id) references user
