create table degree (id bigint generated by default as identity, description varchar(255), name varchar(255), primary key (id))
create table hotel (id bigint generated by default as identity, address varchar(255), city varchar(255), country varchar(255), name varchar(255), state varchar(255), webpage varchar(255), zip_code varchar(255), primary key (id))
create table occupation (id bigint generated by default as identity, description varchar(255), name varchar(255), primary key (id))
create table resto (id bigint generated by default as identity, address varchar(255), city varchar(255), country varchar(255), name varchar(255), state varchar(255), webpage varchar(255), zip_code varchar(255), hotel_id bigint, primary key (id))
create table role (id bigint generated by default as identity, description varchar(255), role_name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, activated boolean, age varchar(255), alias varchar(255), email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), last_visit varchar(255), password varchar(255), reg_date varchar(255), primary key (id))
create table user_degree (user_id bigint not null, degree_id bigint not null)
create table user_occupation (user_id bigint not null, occupation_id bigint not null)
create table user_role (user_id bigint not null, role_id bigint not null)
create table verification_token (id bigint generated by default as identity, expiry_date timestamp, token varchar(255), user_id bigint not null, primary key (id))
alter table user_degree add constraint UK_rivpp4nr7phax525kj5bf83in unique (degree_id)
alter table user_occupation add constraint UK_7o2uqjjtku4v96580ldr71u7p unique (occupation_id)
alter table resto add constraint FK9nini9h4psoxy8e8f4cakip60 foreign key (hotel_id) references hotel
alter table user_degree add constraint FK3sewmi3mt5lxt059onqmi3gnu foreign key (degree_id) references degree
alter table user_degree add constraint FKtngg2al78cbckdfgxbvk0ln56 foreign key (user_id) references user
alter table user_occupation add constraint FKt6vnw35cao97q3oyohj9p66j foreign key (occupation_id) references occupation
alter table user_occupation add constraint FKoap168orrd9c5yboj5krsga5f foreign key (user_id) references user
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user
alter table verification_token add constraint FK_VERIFY_USER foreign key (user_id) references user
